# Generated by Django 4.2.5 on 2024-08-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='natid',
            field=models.CharField(default=1, max_length=14),
            preserve_default=False,
        ),
    ]
