# Generated by Django 4.2.5 on 2024-08-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workfiles', '0001_initial'),
        ('accounts', '0002_customuser_natid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='maindata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='workfiles.maindata'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='natid',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
