# Generated by Django 4.2.5 on 2024-08-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maindata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('natid', models.CharField(max_length=14)),
                ('phone', models.CharField(max_length=11)),
                ('addres_location', models.CharField(max_length=100)),
                ('deg', models.CharField(max_length=50)),
                ('work', models.CharField(max_length=50)),
                ('work_rank', models.CharField(max_length=50)),
                ('frest_work_place', models.CharField(max_length=100)),
                ('carant_work_place', models.CharField(max_length=100)),
                ('work_starting_date', models.DateField()),
                ('hospital_work_starting_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='fileimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_desc', models.CharField(max_length=100)),
                ('imgs', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workfiles.maindata')),
            ],
        ),
        migrations.CreateModel(
            name='breakstime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakstime_desc', models.CharField(max_length=100)),
                ('start_from', models.DateField()),
                ('end_from', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workfiles.maindata')),
            ],
        ),
    ]
