# Generated by Django 4.2.5 on 2025-09-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='carant_work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maindata',
            name='frest_work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
