# Generated by Django 4.2.5 on 2025-09-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workfiles', '0002_alter_maindata_carant_work_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindata',
            name='work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
